- name: Manage IAM users and groups
  hosts: localhost
  vars_files:
    - 'vars/groups.yml'
    - 'vars/users.yml'
  vars:
    sidpasswd: "{{ password }}"
  gather_facts: False
  tasks:
    - name: Statefully manage IAM groups
      iam:
        iam_type: group
        name: "{{ item }}"
        state: "{{ group_opts.state }}"
#       debug:
#           msg: "Item is: {{ item }}"
      with_items: 
        - "{{ aws_groups }}"
      register: new_groups

    - name:
      iam:
        iam_type: user
        name: "{{ item.name }}"
        state: "{{ user_opts.state }}"
        groups: "{{ item.aws_groups }}"
        password: "{{ sidpasswd }}"
      loop: "{{ users }}"
